/** Posts */

export const GET_POSTS = 'GET_POSTS'
export const GET_POSTS_BY_CATEGORY = 'GET_POSTS_BY_CATEGORY'
export const GET_POST_BY_ID = 'GET_POST_BY_ID'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const UP_VOTE_POST = 'UP_VOTE_POST'
export const DOWN_VOTE_POST = 'DOWN_VOTE_POST'
export const EDIT_POST = 'EDIT_POST'
export const DELETE_POST_BY_ID = 'DELETE_POST_BY_ID'
export const RECEIVE_UPDATED_POST = 'RECEIVE_UPDATED_POST'
export const ADD_POST = 'ADD_POST'

/** Categories  */

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const SAVE_CATEGORY = 'SAVE_CATEGORY'

/** Comments */

export const GET_COMMENTS_BY_POST_ID = 'GET_COMMENTS_BY_POST_ID'
export const RECEIVE_COMMENTS = 'RECEIVE_COMMENTS'
export const UP_VOTE_COMMENT = 'UP_VOTE_COMMENT'
export const DOWN_VOTE_COMMENT = 'DOWN_VOTE_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const DELETE_COMMENT_BY_ID = 'DELETE_COMMENT_BY_ID'
export const RECEIVE_UPDATED_COMMENT = 'RECEIVE_UPDATED_COMMENT'
export const ADD_COMMENT = 'ADD_COMMENT'
